import { mkdtemp, readFile, access, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { expect, test } from '@playwright/test';
import { launchElectron } from './helpers/launch-electron';

test('opens a document in the right pane, keeps chat usable, and saves only on request', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'jojo-documents-e2e-'));
  const destination = path.join(directory, 'saved.html');
  const { app, page } = await launchElectron(directory);
  try {
    const externalRequests: string[] = [];
    page.on('request', (request) => { if (request.url().includes('document-preview.invalid')) externalRequests.push(request.url()); });
    await page.getByRole('button', { name: '新建对话' }).click();
    await page.getByPlaceholder('随心输入').fill('E2E: generated document');
    await page.getByRole('button', { name: '发送消息' }).click();
    const entry = page.getByRole('button', { name: '打开文档：稳健选股.html' });
    await expect(entry).toBeVisible();
    await expect(page.locator('.conversation iframe')).toHaveCount(0);
    await expect(page.locator('.artifact-panel')).toHaveCount(0);
    await entry.click();
    const panel = page.getByRole('complementary', { name: '文档预览：稳健选股.html' });
    await expect(panel).toBeVisible();
    await expect(panel.frameLocator('iframe').getByRole('heading')).toHaveText('文档预览测试');
    await expect(panel.frameLocator('iframe').getByRole('heading')).toHaveCSS('color', 'rgb(12, 34, 56)');
    const chatBounds = await page.locator('.chat-pane').boundingBox();
    const panelBounds = await panel.boundingBox();
    expect(panelBounds!.x).toBeGreaterThanOrEqual(chatBounds!.x + chatBounds!.width - 1);
    await expect(page.locator('dialog[open]')).toHaveCount(0);
    await page.getByPlaceholder('随心输入').fill('预览打开时仍然可以输入');
    await expect(page.getByPlaceholder('随心输入')).toHaveValue('预览打开时仍然可以输入');
    const splitter = page.getByRole('separator', { name: '调整文档预览宽度' });
    const workspaceBounds = (await page.locator('.workspace-content').boundingBox())!;
    const handleBounds = (await splitter.boundingBox())!;
    await page.mouse.move(handleBounds.x + 3, handleBounds.y + 100);
    await page.mouse.down();
    await page.mouse.move(workspaceBounds.x + 1, handleBounds.y + 100, { steps: 12 });
    await page.mouse.up();
    await expect(splitter).toHaveAttribute('aria-valuenow', '100');
    expect((await panel.boundingBox())!.width).toBeGreaterThanOrEqual(workspaceBounds.width - 1);
    await expect(page.locator('.chat-pane')).toHaveAttribute('inert', '');
    await page.screenshot({ path: test.info().outputPath('artifact-full-width.png') });
    const fullHandle = (await splitter.boundingBox())!;
    await page.mouse.move(fullHandle.x + 3, fullHandle.y + 100);
    await page.mouse.down();
    await page.mouse.move(workspaceBounds.x + workspaceBounds.width * 0.44, fullHandle.y + 100, { steps: 12 });
    await page.mouse.up();
    await expect(splitter).toHaveAttribute('aria-valuenow', '56');
    await expect(page.getByPlaceholder('随心输入')).toBeEditable();
    await splitter.focus();
    await page.keyboard.press('End');
    await expect(splitter).toHaveAttribute('aria-valuenow', '100');
    await page.getByRole('button', { name: '恢复聊天分栏', exact: true }).click();
    await expect(splitter).toHaveAttribute('aria-valuenow', '56');

    const previewFrame = page.frames().find((frame) => frame.parentFrame());
    expect(await previewFrame!.evaluate(() => typeof (window as unknown as { desktopAgent?: unknown }).desktopAgent)).toBe('undefined');
    expect(await previewFrame!.evaluate(() => { try { localStorage.getItem('test'); return false; } catch { return true; } })).toBe(true);
    expect(externalRequests).toEqual([]);
    await app.evaluate(({ dialog }) => { dialog.showSaveDialog = async () => ({ canceled: true, filePath: '' }); });
    await panel.getByRole('button', { name: '下载保存' }).click();
    await expect(panel.getByRole('button', { name: '下载保存' })).toBeEnabled();
    await expect(access(destination)).rejects.toThrow();
    await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, destination);
    await panel.getByRole('button', { name: '下载保存' }).click();
    await expect(panel.getByRole('status')).toHaveText('文档已保存');
    expect(await readFile(destination, 'utf8')).toContain('<h1>文档预览测试</h1>');
    await page.getByRole('button', { name: '关闭文档预览' }).click();
    await expect(panel).toHaveCount(0);
    expect((await page.locator('.chat-pane').boundingBox())!.width).toBeGreaterThan(chatBounds!.width);
    await page.reload();
    await expect(entry).toBeVisible();
    await expect(page.locator('.artifact-panel, .conversation iframe')).toHaveCount(0);
    await entry.click();
    await expect(panel.frameLocator('iframe').getByRole('heading')).toHaveText('文档预览测试');
  } finally { await app.close(); }
});

test('switches Markdown, images and PDF in one right pane from file entries and references', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'jojo-artifacts-e2e-'));
  const { app, page } = await launchElectron(directory);
  let logs = '';
  app.process().stdout?.on('data', (chunk) => { logs += String(chunk); });
  app.process().stderr?.on('data', (chunk) => { logs += String(chunk); });
  try {
    await page.getByRole('button', { name: '新建对话' }).click();
    const sessions = await page.evaluate(() => window.desktopAgent.listSessions());
    const root = sessions[0]!.workingDirectory;
    await writeFile(path.join(root, 'report.md'), '# Artifact Markdown\n\nA **generated** report.');
    await writeFile(path.join(root, 'chart.svg'), '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect width="120" height="80" fill="teal"/></svg>');
    await writeFile(path.join(root, 'report.pdf'), '%PDF-1.4\n% download test');
    await page.getByPlaceholder('随心输入').fill('E2E: generated artifacts');
    await page.getByRole('button', { name: '发送消息' }).click();
    await expect(page.locator('.artifact-card')).toHaveCount(3);
    await expect(page.locator('.artifact-panel, .conversation iframe')).toHaveCount(0);
    await page.getByRole('button', { name: '打开文档：report.md', exact: true }).click();
    await expect(page.frameLocator('.artifact-panel iframe').getByRole('heading')).toHaveText('Artifact Markdown');
    await page.getByRole('button', { name: '打开文档：chart.svg', exact: true }).click();
    await expect(page.locator('.artifact-panel')).toHaveCount(1);
    await expect(page.getByRole('img', { name: 'chart.svg' })).toBeVisible();
    await expect.poll(() => page.getByRole('img', { name: 'chart.svg' }).evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBe(120);
    await page.locator('.message.assistant .artifact-reference').filter({ hasText: 'report.md' }).click();
    await expect(page.frameLocator('.artifact-panel iframe').getByRole('heading')).toHaveText('Artifact Markdown');
    await page.getByRole('button', { name: '打开文档：report.pdf', exact: true }).click();
    const panel = page.getByRole('complementary', { name: '文档预览：report.pdf', exact: true });
    const destination = path.join(directory, 'saved.pdf');
    await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, destination);
    await panel.getByRole('button', { name: '下载保存' }).click();
    await expect(panel.getByRole('status')).toHaveText('文档已保存');
    expect(await readFile(destination, 'utf8')).toBe('%PDF-1.4\n% download test');
    const openSidebar = page.getByRole('button', { name: '打开左侧对话栏', exact: true });
    if (await openSidebar.isVisible()) await openSidebar.click();
    await page.getByRole('button', { name: '新对话', exact: true }).click();
    await expect(page.locator('.artifact-panel')).toHaveCount(0);
    expect(logs).not.toContain('Artifact not found in this session');
    expect(logs).not.toContain('IPC protocol violation');
  } finally { await app.close(); }
});
